name: Update README Stats

on:
  schedule:
    - cron: "0 3 * * *"   # ежедневно в 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=evgenij-vy&show_icons=true&theme=github_dark&hide_border=true&include_all_commits=true&count_private=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=evgenij-vy&layout=compact&theme=github_dark&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push
        run: |
          mkdir -p profile
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: update readme stats" || exit 0
          git push
